repos:
# MarkDown
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.38.0
  hooks:
  - id: markdownlint
    name: Run markdownlint on your Markdown files
# CommonTextIssues
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
      name: Trims trailing whitespace
    - id: end-of-file-fixer
      name: Makes sure files end in a newline
    - id: mixed-line-ending
      name: Replaces or checks mixed line ending
    - id: check-added-large-files
      name: Prevent giant files from being committed (500kB)
    - id: detect-aws-credentials
      name: Checks for AWS secrets
    - id: fix-encoding-pragma
      name: "Add # -*- coding: utf-8 -*- to the top of python files"
    - id: check-ast
      name: Check whether files parse as valid python
    - id: check-docstring-first
      name: Checks if code is before the docstring
# Python
- repo: https://github.com/PyCQA/docformatter
  rev: v1.7.5
  hooks:
    - id: docformatter
      name: DocFormatter - Format Python docstrings
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.6
  hooks:
    - id: bandit
      name: Bandit - Python common security issues
- repo: https://github.com/PyCQA/flake8
  rev: 6.1.0
  hooks:
    - id: flake8
      name: Flake8 - Style Guide
      types: [python]
      args:
        - --max-line-length=100        # Matching with PyLint default line length
        - --ignore=E126, E501, E722    # line-over-indented, line-too-long, bare-except
- repo: https://github.com/PyCQA/pylint
  rev: v3.0.3
  hooks:
    - id: pylint
      name: Pylint - Static code analyzer
